spring:
  application:
    name: spring-cloud-stream-producer
  cloud:
    stream:
      default:
        producer:
          use-native-encoding: true
      bindings:
        created-user-output:
          destination: streaming.spring-cloud-stream-example.user.created
      kafka:
        binder:
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true

