spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_rest_assured
    username: ${USER}
    password: 123123
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
